# Generated by Django 3.0.5 on 2020-05-01 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200428_1048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='rank',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
